### ISSUE TITLE
 Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by mumbaicat** [wdaglb/ke-buildrouter#1]
Warning: Invalid argument supplied for foreach() in /www/wwwroot/mysite/vendor/ke/buildrouter/src/BuildRouter.php on line 53
php7.1 php7.3都出现，TP5.0，之前还好好的，重装了系统后就这样了。

**Comment by wdaglb** [comment]
> Warning: Invalid argument supplied for foreach() in /www/wwwroot/mysite/vendor/ke/buildrouter/src/BuildRouter.php on line 53
> php7.1 php7.3都出现，TP5.0，之前还好好的，重装了系统后就这样了。

是否注释格式没有编写正确呢？还有版本是否是最新的呢；不介意的话可以加一下我的QQ1207877378我远程看一下
